// GroIntel KNOWLEDGE-1 — World Model Types
export type HypothesisStatus = "candidate" | "monitoring" | "strengthened" | "weakened" | "validated" | "invalidated" | "merged" | "retired";
export type LivingStatus = "active" | "monitoring" | "stale" | "superseded" | "archived";

export interface LivingWorldEntity { id: string; type: string; canonical_name: string; status: LivingStatus; confidence: number; version: number; evidence: string[]; history: { timestamp: string; change: string; confidence: number }[]; created_at: string; updated_at: string; last_reality_event_at: string; }
export interface LivingWorldRelationship { id: string; source_id: string; target_id: string; rel_type: string; status: LivingStatus; confidence: number; version: number; evidence: string[]; history: { timestamp: string; change: string; confidence: number }[]; created_at: string; updated_at: string; last_reality_event_at: string; }
export interface LivingWorldActivity { id: string; category: string; name: string; owner_id: string; status: LivingStatus; confidence: number; version: number; evidence: string[]; history: { timestamp: string; change: string; confidence: number }[]; created_at: string; updated_at: string; last_reality_event_at: string; }
export interface LivingWorldOutcome { id: string; activity_id: string; metric: string; value: number; status: LivingStatus; confidence: number; version: number; evidence: string[]; history: { timestamp: string; change: string; confidence: number }[]; created_at: string; updated_at: string; last_reality_event_at: string; }
export interface LivingWorldCause { id: string; source_type: string; target_type: string; causal_type: string; status: LivingStatus; strength: number; confidence: number; version: number; evidence: string[]; history: { timestamp: string; change: string; confidence: number }[]; created_at: string; updated_at: string; last_reality_event_at: string; }
export interface LivingWorldPattern { id: string; name: string; cluster: string; status: LivingStatus; confidence: number; version: number; evidence: string[]; history: { timestamp: string; change: string; confidence: number }[]; created_at: string; updated_at: string; last_reality_event_at: string; }
export interface WorldModelHypothesis { id: string; statement: string; status: HypothesisStatus; supporting_evidence: string[]; contradicting_evidence: string[]; confidence: number; version: number; created_at: string; updated_at: string; history: { timestamp: string; change: string; status: HypothesisStatus; confidence: number }[]; }
export interface FutureBranch { id: string; name: string; assumptions: string[]; probability: number; confidence: number; trigger_conditions: string[]; supporting_hypotheses: string[]; contradicting_evidence: string[]; expected_outcomes: string[]; risk_level: "low"|"medium"|"high"; opportunity_level: "low"|"medium"|"high"; created_at: string; updated_at: string; }
export interface FutureStateSpace { id: string; name: string; branches: FutureBranch[]; consolidated_probability: number; confidence: number; updated_at: string; }
export interface WorldModelTrace { id: string; action: string; entity_id: string | null; details: string; timestamp: string; }
