-- GroIntel Database Migration 001
-- Company MRI Reports Schema
--
-- This migration creates the core tables for storing Company Intelligence
-- reports generated by the GroIntel Company Intelligence Engine v1.
--
-- Tables in this migration:
--   1. company_mri_reports - Stores generated Company MRI reports
--   2. report_events       - Audit trail for report lifecycle events
--
-- Security:
--   RLS is enabled on both tables.
--   No anon policies exist. These tables must only be accessed
--   through server-side API routes using SUPABASE_SERVICE_ROLE_KEY.
--   Browser clients must NEVER query these tables directly.
--
-- Engine:
--   Reports are generated by src/lib/intelligence/reportGenerator.ts
--   The full CompanyMRI output is stored in report_json for flexibility.
--   Scalar columns (overall_score, growth_score, etc.) enable
--   efficient querying without parsing JSONB.

-- ============================================================
-- Table: company_mri_reports
-- Description: Stores generated Company MRI intelligence reports.
-- Each row represents one generated report for one company domain.
-- ============================================================

create table if not exists company_mri_reports (
  id                uuid        primary key default gen_random_uuid(),
  report_id         text        not null unique,
  company_name      text        not null,
  website           text        not null,
  domain            text        not null,
  industry          text,
  stage             text,
  overall_score     int,
  growth_score      int,
  market_readiness  int,
  competition_risk  int,
  hiring_momentum   int,
  technology_health int,
  expansion_readiness int,
  ai_confidence     int,
  top_opportunity   text,
  top_risk          text,
  recommended_next_action text,
  overview          text,
  report_json       jsonb       not null,
  source            text        default 'engine_v1',
  created_at        timestamptz default now(),
  updated_at        timestamptz default now()
);

-- ============================================================
-- Table: report_events
-- Description: Audit trail for report lifecycle events.
-- Tracks when reports are generated, viewed, exported, etc.
-- The metadata column stores event-specific data as JSONB.
-- ============================================================

create table if not exists report_events (
  id         uuid        primary key default gen_random_uuid(),
  report_id  text        not null,
  event_type text        not null,
  metadata   jsonb       default '{}'::jsonb,
  created_at timestamptz default now()
);

-- ============================================================
-- Indexes
-- Purpose: Optimize common query patterns
-- ============================================================

-- Lookup reports by generated report_id
create index if not exists idx_company_mri_reports_report_id
  on company_mri_reports (report_id);

-- Lookup reports by company domain
create index if not exists idx_company_mri_reports_domain
  on company_mri_reports (domain);

-- List reports newest first (dashboard use case)
create index if not exists idx_company_mri_reports_created_at_desc
  on company_mri_reports (created_at desc);

-- Lookup events by report
create index if not exists idx_report_events_report_id
  on report_events (report_id);

-- Filter events by type (analytics use case)
create index if not exists idx_report_events_event_type
  on report_events (event_type);

-- ============================================================
-- Row Level Security
-- Purpose: Enforce server-only access pattern.
-- No anon or authenticated policies will be created.
-- All access must use the service role key from server-side API.
-- ============================================================

alter table company_mri_reports enable row level security;
alter table report_events enable row level security;

-- No policies created.
-- RLS is enabled but no access is granted to any role.
-- Only service_role (bypassing RLS) can read/write these tables.

-- ============================================================
-- Notes for Supabase Dashboard display
-- ============================================================

comment on table company_mri_reports is
  'Company MRI intelligence reports generated by the GroIntel Company Intelligence Engine v1. Server-only access via SUPABASE_SERVICE_ROLE_KEY. Browser must NOT query directly.';

comment on column company_mri_reports.report_json is
  'Full CompanyMRI output from src/lib/intelligence/types.ts. Contains growth opportunities, key risks, market recommendations, hiring recommendations, competitive signals, technology signals, and action plans.';

comment on table report_events is
  'Audit trail for report lifecycle events. Tracks generate, view, export, and other events. Only accessible via server API with service role key.';

-- End of migration 001
